### ISSUE TITLE
Error on line 46 in grid-field-formatter.tpl.php file

### ISSUE THREAD

**Issue by MikheevDesign** [backdrop-contrib/grid_field_formatter#1]
After creating the material, I received a parsing error, after which I slightly changed the code and everything works, here is my code that needs to be added to line 46:
`<div class="<?php print implode(' ', $classes); ?>"<?php print backdrop_attributes($attributes); ?>>
`

**Comment by Retsell** [comment]
Thank you @MikheevDesign. Correction made.
